# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: cargo-check
        name: 'relearn-check'
        args: ['--all-targets']
    -   id: cargo-check
        name: 'relearn-derive-check'
        args: ['--all-targets', '--manifest-path', 'relearn_derive/Cargo.toml']
        always_run: true
    -   id: cargo-check
        name: 'relearn-experiments-check'
        args: ['--all-targets', '--manifest-path', 'relearn_experiments/Cargo.toml']
        always_run: true
