[package]
name = "rust-rl"
version = "0.1.0"
authors = ["Eric Langlois <eric@langlois.xyz>"]
edition = "2018"
description = "Run reinforcement learning experiments"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# To get
# https://github.com/clap-rs/clap/issues/2022
# https://github.com/clap-rs/clap/issues/2528
clap = { git = "https://github.com/clap-rs/clap.git", branch = "master" }
enum-map = "1.1"
impl-trait-for-tuples = "0.2"
lazycell = "1.3"
ndarray = "0.15"
ndarray-stats = "0.5"
num-traits = "0.2"
once_cell = "1.8"
rand = "0.8"
rand_distr = "0.4"
rust_rl_derive = { path = "rust_rl_derive" }
smallvec = { version = "1.6", features = ["union"] }
tch = "0.5"
thiserror = "1.0"

[dev-dependencies]
rstest = "0.7.0"
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "rust"
harness = false

[[bench]]
name = "features"
harness = false

[[bench]]
name = "rnn"
harness = false

[[bench]]
name = "tch"
harness = false
