[package]
name = "rust-rl"
version = "0.1.0"
authors = ["Eric Langlois <eric@langlois.xyz>"]
edition = "2018"
description = "Run reinforcement learning experiments"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
enum-map = "0.6.4"
ndarray = "0.14.0"
ndarray-stats = "0.4"
rand = "0.8.3"

[dev-dependencies]
rstest = "0.7.0"
