[package]
name = "rust-rl"
version = "0.1.0"
authors = ["Eric Langlois <eric@langlois.xyz>"]
edition = "2018"
description = "Run reinforcement learning experiments"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# To get https://github.com/clap-rs/clap/issues/2022
clap = { git = "https://github.com/clap-rs/clap.git", branch = "master" }
enum-map = "0.6.4"
lazycell = "1.3"
ndarray = "0.14.0"
ndarray-stats = "0.4"
rand = "0.7.3"
rust_rl_derive = { path = "rust_rl_derive" }
statrs = "0.13.0"
# To get https://github.com/LaurentMazare/tch-rs/issues/336
tch = { git = "https://github.com/LaurentMazare/tch-rs.git", branch = "master" }
thiserror = "1.0"

[dev-dependencies]
rstest = "0.7.0"
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "rnn"
harness = false

[[bench]]
name = "tch"
harness = false
